### PR TITLE
User validation

### PR DESCRIPTION
**Pull request by versh23**
Use symfony validation

### CODE REVIEW

**Comment by bobdenotter** [comment]
@versh23 Thanks!  👍 

Travis is being weird, so tests aren't working correctly yet. I'll probably check it properly tomorrow!

**Comment by versh23** [comment]
Still work in progress ;)

**Comment by bobdenotter** [comment]
@versh23 Ah, OK! ping you want to a second pair of eyes! :-)

**Comment by versh23** [comment]
@bobdenotter green :)

**Pull request merged**
