### PR TITLE
Drop `UNIQUE` constraint for bolt_user_auth_token.user_id

### PR DESCRIPTION
**Pull request by I-Valchev**
Introduced intentionally in #2912. This fixes #2912 as a BC change.

### CODE REVIEW

**Comment by bobdenotter** [comment]
You've mentioned #2912 twice.. Did you intend to name another one?

**Comment by I-Valchev** [comment]
Nope, not really. 😅 An odd way to express it, haha, my "Bulglish" I guess

**Review by bobdenotter — APPROVED** [review]
👍

**Review by Joossensei — COMMENTED** [review]
👍🏻

**Pull request merged**
