### PR TITLE
fix edit file in File management subfolders

### LINKED ISSUE #1914: File management: deleting/duplicating files in a subfolder
Can't remove or duplicate files in a subfolders in `File management` section

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version |  4.0 / master
| Install type                   |  Composer install / GitHub checkout
| BC Break                     | yes/no
| PHP version                 | 7.2
| Web server                  | Built-in, version [ sf 5.1]
| For UX/UI issues        | Chrome latest

Reproduction
------------

### Steps to reproduce

- assign attribute `upload: somefolder` for `image type` in a `config\bolt\contenttypes.yaml`
- add some image for your content
- go to `File management` section, find your folder
- try to delete or duplicate your file

### Expected result

- success file deleting or duplicating 
- return to the destination folder

### Actual result

- return to the root location (files)
- in case of duplicate we see duplicated file in a root
- in case of delete we have success notification but the file in a subfolder actualy does not deleted

### PR DESCRIPTION
**Pull request by denis-gorin**
Fixes #1914 

- add path for subfolder to delete/duplicate action
- add path to return after action
- replace success notification label for duplicate action

### CODE REVIEW

**Review by I-Valchev — CHANGES_REQUESTED** [review]
hi @denis-gorin , good stuff thanks for fixing it!

Looks like it needs a csfix, you can run that by running `make csfix` from the root folder of your clone, then push the changes and the tests should pass. Can you do that? :-)

**Comment by denis-gorin** [comment]
> make csfix

Ufortunatelly, I'm not on a UNIX-like system is there another way to run csfixer?

**Comment by I-Valchev** [comment]
@denis-gorin maybe try to run this "manually"?
```
bin/console c:c
vendor/bin/ecs check src
vendor/bin/ecs check tests/spec
vendor/bin/ecs check tests/php
vendor/bin/phpstan --memory-limit=1G analyse -c phpstan.neon src
```

**Comment by denis-gorin** [comment]
> vendor/bin/phpstan --memory-limit=1G analyse -c phpstan.neon src

yes, found it in README
already pushed
but last command (phpstan.neon) trow error:

``` console
In Resolver.php line 110:

  Service '0296': Class Symplify\CodingStandard\Rules\ForbiddenFuncCallRule not found.
```

**Review by I-Valchev — APPROVED** [review]
@denis-gorin thanks, it looks good now! Let's wait for the last couple of tests to pass and we're good to merge.

**Review by bobdenotter — APPROVED** [review]
Tests passing! 👍

**Pull request merged**
