### PR TITLE
fix for issue #1286 search/setcontent on selectfields with multiple entries. 

### PR DESCRIPTION
**Pull request by JTNMW**

### CODE REVIEW

**Comment by bobdenotter** [comment]
@JTNMW You can run `make csfix` on the command line, and it'll fix the Code Style issues for you. :-)

**Comment by JTNMW** [comment]
small addition to selectQuery.php. Enables taxonomies to be included in contenttype filtering at the backend UI.

**Comment by JTNMW** [comment]
sorry, apologies for any coding style errors if they are causing problems. Do i run csfix on command line whilst in app project dir. this what i get back. any advice?
make csfix
make csclear
mkdir -p var/cache/ecs
chmod -R a+rw var/cache/ecs
rm -rf var/cache/ecs/*
vendor/bin/ecs check src --fix
bash: vendor/bin/ecs: No such file or directory
make: *** [csfix] Error 127

**Comment by bobdenotter** [comment]
You'll need to run this in the root folder of a checkout of `bolt/core`, instead of `bolt/project`. 

I've run this now, and pushed to your branch.. You'll have to `git pull` to fetch it. 

Let's see what the tests say now. :-)

**Comment by JTNMW** [comment]
You may want to revert back to the first of the selectQuery.php files i submitted 50708be . The changes in 775ad38 is causing an issue at the frontend which i wasn't aware of when making the pull request. I'll see if i can get this working correctly.

**Comment by bobdenotter** [comment]
Updated.. :-)

**Comment by bobdenotter** [comment]
Ok, seems like there's some quirks or side-effects. I'll see what I can find.

**Comment by JTNMW** [comment]
@bobdenotter it seems that json_contains() function is not available with sqlite. I'm not sure what the equivalent function is in sqlite. Is this causing the issue you are finding? I'll see if i can find a work around.

**Comment by bobdenotter** [comment]
@JTNMW Hmm, could be that that's not readily available, yes.. For JSON_EXTRACT, we've implemented our own method to add it to the https://github.com/ScientaNL/DoctrineJsonFunctions library. 

It _should_ be supported now, though. See here: https://github.com/ScientaNL/DoctrineJsonFunctions/issues/49 

could it be that _your_ local SQLite version doesn't support it, yet? We've found out there's no real way to see if SQLITE supports JSON or not, other than guessing by a few known cases. See here: https://github.com/bolt/core/blob/master/src/Doctrine/Version.php#L16

**Comment by JTNMW** [comment]
@bobdenotter Workaround so that multiselect fields can be searched without the need for JSON_CONTAIN(). Ive tested this on SQLite and MySQL and seems to work fine. Snippet of code added to allow taxonomies to be searched as part of the backend contenttype Filter (anyField).

**Comment by JTNMW** [comment]
Sorry for error on my part, but I discovered that the foreach loop of taxonomies was causing memeory exhuastion. Ive removed the loop and search/setcontent with anyField now performs fine. ive done a new pr with the modification #1619.

**Pull request merged**
