### PR TITLE
Bootstrap upgrade from v4 to v5

### PR DESCRIPTION
**Pull request by nestordedios**

### CODE REVIEW

**Comment by nestordedios** [comment]
When this changes are released this https://github.com/bobdenotter/configuration-notices/pull/19 has to be released too. They are related

**Comment by nestordedios** [comment]
Hi 👋 !!

This PR is ready to be reviewed and tested.

The main thing this PR does is migrating from Bootstrap v4 to v5. It replaces the Bootbox library and uses Bootstrap modals instead and adds a couple of new translations

Images and Files are no longer selected from a select list but from a modal displaying the different resources. See screencasts below:
**File modal:** http://g.recordit.co/RExHfrtLKt.gif
**Image modal:** http://g.recordit.co/Rd7onrcsup.gif

**Comment by nestordedios** [comment]
As @Joossensei pointed out. The items in the list below need to be fixed before merging in.

- [ ] The navigation tabs on a record dont seem to work
- [ ] As we discussed we need a Delete confirmation modal
- [ ] The compact view button on listing pages doesnt work
- [ ] The bulk select also doesnt work
- [ ] Theres also an issue with the Image and File lists but that seems to be an issue with Cypress. It wont click the ‘Save changes’ button at the bottom of the modal

**Review by bobdenotter — APPROVED** [review]
Great work, @nestordedios and @Joossensei 👍

**Pull request merged**
