### PR TITLE
Fix incorrect error when uploading an allowed filetype, that isn't an image

### PR DESCRIPTION
**Pull request by bobdenotter**
For example, you have this: 

```yaml
accept_file_types: [ …, mp4, …]

accept_media_types: [ gif, jpg, jpeg, png, svg, pdf, mp3, tiff, avif, webp ]
```

Uploading an `mp4` into a `type: file` field _should_ work, but it doesn't, because it doesn't generate a Media Entity. This PR fixes that.

Screenshot 2021-06-29 at 20 07 50

### CODE REVIEW

**Review by I-Valchev — CHANGES_REQUESTED** [review]
@bobdenotter there are a couple of these `isImage` methods now, see here:
https://github.com/bolt/core/search?q=isimage 

Should we refactor?

**Comment by bobdenotter** [comment]
Yeah, let's see if we can! 

The methods do something similar, but not exactly the same (one operates on a string, the other on `Media`. But, that hardcoded list in two places in an eyesore. :-)

**Comment by bobdenotter** [comment]
Updated!

**Comment by bobdenotter** [comment]
This is becoming a snake pit, and the PR is getting much too large. Going to close this one, open a new one, and leave the refactoring for later. 

See #2663

**Pull request closed without merging**
