### PR TITLE
Remove unneeded `security_checker.yaml` migration

### PR DESCRIPTION
**Pull request by bobdenotter**
Clean up leftover from #2605

### CODE REVIEW

**Comment by bobdenotter** [comment]
For reference, as pointed out on Slack: 

Screenshot 2021-06-14 at 10 26 20

**Review by I-Valchev — APPROVED** [review]
👍

**Review by mcdennem — APPROVED** [review]
Nice!

**Review by nestordedios — APPROVED** [review]
NIce! 👍

**Pull request merged**
