### PR TITLE
Simplified Chinese translation

### PR DESCRIPTION
**Pull request by ziselive**
Chinese translation Initial submission.

### CODE REVIEW

**Comment by simongroenewolt** [comment]
For what it's worth: I just checked about 25 translations by translating them back to English using google translate, they all looked fine.

**Comment by ziselive** [comment]
@simongroenewolt  Some words can be literally translated, and some words need to be translated according to their function.

**Comment by I-Valchev** [comment]
Fantastic, thanks @ziselive .

To be precise, this is Simplified Chinese, correct? If so, do you mind if I update the PR name to reflect that? :-)

**Comment by ziselive** [comment]
@I-Valchev  Hello, this is simplified Chinese. Can be modified.

**Review by bobdenotter — APPROVED** [review]
Awesome, Thank you @ziselive 👍 

And @simongroenewolt for doing some manual checks! ;-)

**Pull request merged**
