### PR TITLE
Feature/image attrib option

### LINKED ISSUE #941: Support image attrib option

### PR DESCRIPTION
**Pull request by I-Valchev**
Fixes #941

### CODE REVIEW

**Comment by bobdenotter** [comment]
Hmm, let's discuss this one.. Didn't we decide to _drop_ the `title` attrib earlier, in favor of using the attributes from the Media entity?

**Comment by I-Valchev** [comment]
@bobdenotter makes sense to me, I'm changing this to WIP and will instead do what we discussed

**Comment by I-Valchev** [comment]
👌 ☺️ super

**Comment by ionutlip** [comment]
Hi @bobdenotter / @I-Valchev   this feature  did not reach the bolt 5  ?

**Pull request merged**
