### PR TITLE
Fix htmllang() when no locales defined

### PR DESCRIPTION
**Pull request by I-Valchev**
Fixes htmllang part of #1437

### CODE REVIEW

**Comment by milosa** [comment]
My `htmllang()` is still empty in RC 23.

**Comment by bobdenotter** [comment]
@milosa Does that install have `bobdenotter/configuration-notices` ? ;-)

**Comment by milosa** [comment]
@bobdenotter Yes, it does. I tried it on a clean install.

**Comment by peterboorsma** [comment]
I can confirm @milosa 's findings.
The `{{htmllang()}}` tag remains empty in RC23. In my case only on a site with 1 language and no locales in `contenttypes.yaml`.

**Pull request merged**
