### PR TITLE
Allow prefix and postfix text on relationships and taxonomies input field

### LINKED ISSUE #2989: Prefix and postfix text options are not visible on relationships and taxonomies
Having a taxonomy definition like it's shown below does not add the `prefix` or `postfix` text to the taxonomy input field.
```
tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    prefix: "My prefix text"
    postfix: "My postfix text"
    allow_spaces: false
    required: false
```

Having a relation definition like it's shown below does not add the `prefix` or `postfix` text to the taxonomy input field.

```
relations:
        entries:
            prefix: "My prefix text"
            multiple: false
            label: "Choose an entry"
            order: -id
            format: "{title} (№ {id}, {status})"
            postfix: "My postfix text"
```

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.0.6
| Install type                                          | Composer install
| PHP version                                           | 7.3 |
| Web server                                            | Symfony local server

Reproduction
------------

Add the mentioned definitions to the contenttype.yaml and taxonomy.yaml

### Expected result

The prefix and postfix text is displayed on the related input field

### Actual result

The prefix and postfix text is **not** displayed on the related input field.

### PR DESCRIPTION
**Pull request by nestordedios**
Fixes #2989

### CODE REVIEW

**Review by I-Valchev — COMMENTED** [review]
Hey @nestordedios,
Good issue and good PR! :-)

The formatting of the prefix is certainly quite specific. This here and the one in https://github.com/bolt/core/blob/master/templates/_partials/fields/_base.html.twig#L123-L132 are quite similar. Is it a good idea to put them in a macro that is used in both places?

**Comment by nestordedios** [comment]
Hey @I-Valchev, yes I agree!

I'll work on it and and update the PR 👍

**Review by I-Valchev — APPROVED** [review]
✅ Nice! Thanks @nestordedios

**Review by bobdenotter — APPROVED** [review]
Nice! 👍

**Pull request merged**
