### PR TITLE
Put back some more files that we really do need.

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Review by I-Valchev — APPROVED** [review]
Less = more! 👍

**Comment by XWB** [comment]
@bobdenotter Can you tag a new release, 4.1.2 is broken due to the absence of package.json

**Comment by bobdenotter** [comment]
@XWB What is broken, exactly? I didn't think it was needed in normal use (except for when you're building the assets yourself, which I assume most people don't do)

**Comment by XWB** [comment]
Our pipeline fails because it cannot find package.json since 4.1.2:

```bash
$ make build-assets
cd vendor/bolt/core && npm install && npm run build
npm WARN saveError ENOENT: no such file or directory, open 'vendor/bolt/core/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'vendor/bolt/core/package.json'
npm WARN core No description
npm WARN core No repository field.
npm WARN core No README data
npm WARN core No license field.
up to date in 0.313s
found 0 vulnerabilities
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path vendor/bolt/core/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open 'vendor/bolt/core/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitlab-runner/.npm/_logs/2020-10-21T11_15_21_125Z-debug.log
Makefile:20: recipe for target 'build-assets' failed
make: *** [build-assets] Error 254
Cleaning up file based variables
00:00
ERROR: Job failed: exit status 1
```

**Comment by bobdenotter** [comment]
Why does your pipeline do this, instead of simply pulling in `bolt/assets` and/or running `bin/console bolt:copy-assets` ?  saves a good minute or two each run.

**Comment by bobdenotter** [comment]
@XWB We've tagged `4.1.3`, but i'm still curious why you're doing it this way.. Not to say you _shouldn't_ do this, but i'm always interested to learn about people's workflows.

**Pull request merged**
