### PR TITLE
[ci] use common path for .env file

### PR DESCRIPTION
**Pull request by TomasVotruba**
Follow up to https://github.com/bolt/core/pull/1918#discussion_r497389047

This move makes it less surprising, and saves extra steps on CI and on local development.

<br>

See 2018 post from Symfony blog:

image

https://symfony.com/doc/current/configuration/dot-env-changes.html

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ready to merge :+1:

**Review by bobdenotter — APPROVED** [review]
Let's roll with this! 

We ourselves will get used to using `.env.local` files, if that's the standard way to do things now! 👍

**Comment by I-Valchev** [comment]
Oh, that's good to know!

**Comment by TomasVotruba** [comment]
Wow, that's fast :) Thanks

**Pull request merged**
