### PR TITLE
Fix deprecation in RouteCollectionBuilder

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Review by I-Valchev — APPROVED** [review]
Clean code, up-to-date code! 👍

**Comment by XWB** [comment]
@bobdenotter This change results in the following error:

> Argument 1 passed to Bolt\Kernel::configureRoutes() must be an instance of Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator, instance of Symfony\Component\Routing\RouteCollectionBuilder given, called in vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php on line 93

Symfony 4.4.13

**Comment by bobdenotter** [comment]
@XWB Could you update to SF 5? I assume you're on an older 4.0 beta/RC that you've ran `composer update` on, right? 

See here: https://github.com/bolt/project/blob/master/composer.json#L48-L54

**Comment by XWB** [comment]
@bobdenotter Thanks, you're right. Updating to Symfony 5.1 resolves my issue.

**Pull request merged**
