### PR TITLE
If the given "values" for a `type: select` is not a string like `pages/{title}`, we shouldn't parse it

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by bobdenotter** [comment]
Let's park this one for now.. There's more to it than is seems at first sight.

giphy

**Comment by simongroenewolt** [comment]
Hmm @bobdenotter this looks a lot like my issue https://github.com/bolt/core/issues/3085. Please don't just ignore the null value, as at least in my situation there _should_ not have been a null and the real problem is in the initialization of the select field.

**Comment by bobdenotter** [comment]
@simongroenewolt Yes, I'm now quite certain that the underlying issue here is what you're seeing in #3085. Especially now that i'm able to reproduce it reliably.

**Comment by bobdenotter** [comment]
Fixed in #3101

**Pull request closed without merging**
