### PR TITLE
removed vibrant as cdn and added it using packagemanger

### PR DESCRIPTION
**Pull request by UtechtDustin**
This pullrequest removes the cdn of vibrant and adds a new javascript file for it.

### CODE REVIEW

**Comment by UtechtDustin** [comment]
I dont understand the lint errors, what does it mean ?
e.g. 
```
Replace `············` with `········` 
```

**Comment by UtechtDustin** [comment]
@I-Valchev could you explain me the lint errors ?

**Comment by I-Valchev** [comment]
@UtechtDustin It seems this has to do with indentation. prettier complains about the number of spaces in your initial version.
Is that right, @bobdenotter ?

**Comment by bobdenotter** [comment]
@I-Valchev Yes, that's correct. But I suppose @UtechtDustin figured it out as well, as his last commit fixed it. :-)

**Comment by UtechtDustin** [comment]
Thank you for the information.
I dont figured it out i just run the `lint-fix`command :-)

**Pull request merged**
