### PR TITLE
Remove 4.x deprecations

### PR DESCRIPTION
**Pull request by I-Valchev**
If this is accepted, we need to fix https://github.com/bolt/newswidget/issues/6

### CODE REVIEW

**Review by bobdenotter — APPROVED** [review]
👍

**Comment by I-Valchev** [comment]
@bobdenotter I really don't know why this is failing, can we take a look at it together? 🤔

**Comment by bobdenotter** [comment]
All fixed up! 🛠️

**Review by bobdenotter — APPROVED** [review]

**Comment by I-Valchev** [comment]
Nice, thanks! 👍

**Pull request merged**
