### PR TITLE
Create `bin/console server` command, to easily start webserver

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Review by nestordedios — APPROVED** [review]
It looks good! 👍 Cool PR for those using Symfony Web Server!! 🚀

**Comment by I-Valchev** [comment]
hey! Code looks good, is there some story behind why we'd want to add something like this?

**Review by nestordedios — APPROVED** [review]
Looks good! 👍

**Review by mcdennem — APPROVED** [review]
👍

**Pull request merged**
