### PR TITLE
Collapsible collections

### PR DESCRIPTION
**Pull request by I-Valchev**
image

image

### CODE REVIEW

**Comment by bobdenotter** [comment]
Looks good so far! Were you planning on modifying the "Add" menu to be a bit more like it was in Bolt 3? 

Here's an example I found on one of our sites (NTS): 

Schermafbeelding 2020-09-08 om 10 44 58

**Comment by I-Valchev** [comment]
@bobdenotter yes I tried that but there's an issue with the multi-select tool we us. Its docs say that you can listen to the `select` event when something is clicked (hence when we add a new item), but in reality that only works like `onchange`. That doesn't work for us.

I'm creating an issue for it here https://github.com/shentao/vue-multiselect/issues/1324

**Comment by bobdenotter** [comment]
Maybe it shouldn't be a Vue-select thingy, but just a simple dropdown button: 

https://getbootstrap.com/docs/4.0/components/dropdowns/

**Comment by eduardomart** [comment]
May I suggest an option for showing icons only? as opposed to icon and label on each button for move/up/down/delete :-)

**Comment by I-Valchev** [comment]
@eduardomart I think that's one of the things that advanced users of Bolt are going to appreciate (less crowded interface, more space), but for people starting out with the CMS there's a high chance it won't be clear what those buttons are for.

Right now, let's merge this in as is and think about improving it further still!

**Review by bobdenotter — APPROVED** [review]
Whoop whoop!

**Pull request merged**
