### PR TITLE
Styling Collections more nice-like

### PR DESCRIPTION
**Pull request by bobdenotter**
Before: 

Schermafbeelding 2020-09-18 om 17 22 02

After: 

Schermafbeelding 2020-09-18 om 17 18 48

### CODE REVIEW

**Review by I-Valchev — APPROVED** [review]
Awesome!! 😍

**Comment by bobdenotter** [comment]
@I-Valchev Thanks! I'm going to fix up the tests today, and probably some fine-tuning, but then i think it's good to go! :-)

**Comment by I-Valchev** [comment]
@bobdenotter perfect. The set also looks really good this way, does it look the same standalone?

**Comment by bobdenotter** [comment]
@I-Valchev Yes. I figured the "THIS IS INSIDE A SET" could be less prominent. It's usually irrelevant for an Editor.

**Comment by I-Valchev** [comment]
@bobdenotter for sure. I really love the new look! 👏

**Pull request merged**
