### PR TITLE
[CI] Move console checks from Travis to Github Actions

### PR DESCRIPTION
**Pull request by TomasVotruba**
Follow up to https://github.com/bolt/core/pull/1916

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ready to merge :heavy_check_mark:

**Review by bobdenotter — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :+1: 

Btw, do you any questions or WTFs in your mind? 
I want this transition to be clear and safe to you, so don't hesitate and ask about any single silly weird line you see.

**Comment by bobdenotter** [comment]
So far it seems straightforward! I suppose the "tricky" part will be Behat. It's the part that fails most often on Travis for dubious reasons, and if I recall correctly, it was also the most complex to get working. 

Tomorrow @I-Valchev will be at work again, so i'm sure he'll chime in as well! :-)

**Comment by TomasVotruba** [comment]
That's great, I never worked with Behat so that should not be a problem ;)

<br>

I see some first complications - https://github.com/bolt/core/runs/1177089242

It might be caused by incorrect `composer.json` setup:

```bash
       "post-install-cmd": [
            "php bin/console extensions:configure --with-config",
            "@auto-scripts",
            "php bin/console bolt:info"
        ],
        "pre-package-uninstall": [
            "php bin/console extensions:configure --remove-services"
        ],
        "post-update-cmd": [
            "php bin/console extensions:configure",
            "@auto-scripts",
            "php bin/console bolt:info"
        ],
        "auto-scripts": {
            "cache:clear --no-warmup": "symfony-cmd",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
        },
```

This is seems like a project `composer.json`, e.g [symfony/demo](https://github.com/symfony/demo/blob/e5e5a8fff048351ea8a8fe2b418f0256eabeee12/composer.json#L75-L85) or [laravel/laravel](https://github.com/laravel/laravel/blob/a6ca5778391b150102637459ac3b2a42d78d495b/composer.json#L50-L59)


I've found these line in [bolt/project](https://github.com/bolt/project/blob/b42dc1feb5c82952e12875096586ec6d4afc4fff/composer.json#L25-L43)

Saying that, what are those needed for here?

**Comment by I-Valchev** [comment]
@TomasVotruba @bobdenotter Yes I also think it's pretty clear and understandable. Good to know that we have console colours by adding `--ansi`. Thanks Tomas!

**Pull request merged**
