### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by rixbeck**
# Branch contains 
- texts as translation definition entries passed as attributes in VUE components and corresponding twig templates 
- texts as translation entries in twig templates
- updated english and hungarian `xlf` files. (Dutch updated to be containing dummy definition entries)
- code styling in templates regarding line length, html tag attribute order

### CODE REVIEW

**Comment by bobdenotter** [comment]
Travis is giving this error: 

```
[13:16:35] [webpackbar] [INFO] Compiling Webpack

 92% chunk asset optimization OptimizeCssAssetsWebpackPluginBrowserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`

 94% after seal ERROR  Failed to compile with 1 errors     
```

@rixbeck I'm fairly certain that this issue is not caused by your work, but by something else.. I'll take a look!

**Comment by rixbeck** [comment]
@bobdenotter I reverted package.json to the "original" where I was branched and pushed with lock. Made a clean rebuild here wo. problem. I hope it solves.

**Comment by bobdenotter** [comment]
@rixbeck It's still giving that same error. I'm certain it's some breakage in NPM / Webpack.. I'll take a better look tomorrow, and we'll sort it out. :-)

**Comment by bobdenotter** [comment]
Found the problem! It's upstream, in a module named Consola:

```
$ npm run build

> bolt@4.0.0-beta.1 build /home/travis/build/bolt/core

> encore production --progress

Running webpack ...

/home/travis/build/bolt/core/node_modules/consola/dist/consola.js:1

(function (exports, require, module, __filename, __dirname) { "use strict";function _interopDefault(u){return u&&"object"==typeof u&&"default"in u?u.default:u}var util=_interopDefault(require("util")),path=require("path"),fs=require("fs"),os=_interopDefault(require("os")),commonjsGlobal="undefined"!=typeof globalThis?globalThis:"undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{};function createCommonjsModule(u,e){return u(e={exports:{}},e.exports),e.exports}function getCjsExportFromNamespace(u){return u&&u.default||u}var vendors=[{name:"AppVeyor",constant:"APPVEYOR",env:"APPVEYOR",pr:"APPVEYOR_PULL_REQUEST_NUMBER"},{name:"Bamboo",constant:"BAMBOO",env:"bamboo_planKey"},{name:"Bitbucket Pipelines",constant:"BITBUCKET",env:"BITBUCKET_COMMIT"},{name:"Bitrise",constant:"BITRISE",env:"BITRISE_IO",pr:"BITRISE_PULL_REQUEST"},{name:"Buddy",constant:"BUDDY",env:"BUDDY_WORKSPACE_ID",pr:"BUDDY_EXECUTION

SyntaxError: Unexpected token ...

    at NativeCompileCache._moduleCompile (/home/travis/build/bolt/core/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)

    at Module._compile (/home/travis/build/bolt/core/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
```

There's an issue open for it, here: https://github.com/nuxt/consola/issues/56

**Comment by bobdenotter** [comment]
Two out of three tests are passing now, except for one that's giving a network timeout.. Annoying! 

Screenshot 2019-08-08 at 08 52 49

**Comment by rixbeck** [comment]
> Found the problem! It's upstream, in a module named Consola:
> 
Nice catch, Bob!

**Pull request merged**
