### PR TITLE
[RFC][WIP] Introduce Symfony Forms

### LINKED ISSUE #331: Implement Symfony Forms and Validation in backend
Refactor forms that are currently used.
Introduce user-defined field validation.
Unit test everything.

### PR DESCRIPTION
**Pull request by JarJak**
Let's use Symfony Forms everywhere.

Advantages:
- CQRS security by default
- unit testable
- front-end and back-end validation
- allows adding custom validation to any field
- ability to use form themes for fields
- allow adding more field types (by extensions?)

TODO:
- frontend / Vue components need to follow up
- Manual tests: Check if all fields, relations, taxonomies are saved correctly. Test if validation works as expected.
- E2E tests won't pass until some frontend dev will fix forms in twig.

Closes #331

### CODE REVIEW

**Comment by bobdenotter** [comment]
When the other open stuff is merged in, i'll take a closer lok at this, and see if I can help out with the "frontend" stuff as well. Neat!

**Comment by JarJak** [comment]
Reminder: I have to rebase this PR and resolve conflicts.

**Comment by bobdenotter** [comment]
This is the error i'm getting now:

Schermafbeelding 2019-03-22 om 14 11 32

**Comment by bobdenotter** [comment]
Getting a bit further than before now.. Currently getting this error when trying to edit any record: 

Schermafbeelding 2019-03-27 om 09 07 54

**Comment by bobdenotter** [comment]
@JarJak Gentle nudge.. Any progress on this PR? :-)

**Comment by JarJak** [comment]
@bobdenotter This error might be related to ConfigParser. FieldType and DeepCollection are both collections. Can you debug it?

**Comment by bobdenotter** [comment]
> This error might be related to ConfigParser. Looks like field definition is parsed into an invalid collection class. FieldType and DeepCollection are both collections. Can you debug it?

My plan for this weekend was to do this refactoring for the configparser (with tests) we discussed earlier. When that's done, I'm fairly certain I can sort this one out to. 
(First we need to merge #376 though.. `*hint*` `*hint*`)

**Comment by bobdenotter** [comment]
> This error might be related to ConfigParser. Looks like field definition is parsed into an invalid collection class. FieldType and DeepCollection are both collections. Can you debug it?

Thinking about this some more.. I quickly edited the typehints to be a general `Collection`, so both types would pass. 

Next error is this one: 

Screenshot 2019-04-05 at 07 16 21

I will keep working on cleaning up the configparsers in the meantime.

**Comment by bobdenotter** [comment]
Bumping this to a later version. When you have time to work on this again, we can schedule it for the then-next upcoming milestone

**Comment by bobdenotter** [comment]
This PR has been more than half a year ago. @JarJak , if you want to finish it, let me know what I can do to help.

**Comment by JarJak** [comment]
@bobdenotter this PR needs a follow-up by Vue components to make them compatible with Symfony Forms templates. Please relate to https://symfony.com/doc/current/form/form_themes.html

I can fix conflicts in next week

**Comment by bobdenotter** [comment]
@JarJak I don't think just fixing the conflicts is enough.. This is currently not something that somebody else can pick up and fix. It needs to actually _work_, before we can task someone to build upon it.

**Comment by bobdenotter** [comment]
This PR has been lingering for two and a half years now. I think it's time to close it. 😔

**Pull request closed without merging**
