### PR TITLE
Fix 404 emptyimage

### PR DESCRIPTION
**Pull request by Wieter**
Fix for #2079

### CODE REVIEW

**Comment by Wieter** [comment]
WIP because there is another minor fix, but I'm a bit stuck there: 
while accessing http://../bolt/edit/54#media:
https://github.com/bolt/core/blob/50e6f1baf283df112a820d97fbaea6d536079848/assets/js/app/editor/Components/Select.vue#L30 `empty: props.option.value == ''` --> TypeError: Cannot read property 'value' of undefined

And another which I've not yet been able to trace back (0.js:formatted:46090), seems to be all related.

**Review by bobdenotter — APPROVED** [review]
Nice catch! Thanks, @Wieter

**Comment by Wieter** [comment]
You're welcome!

https://github.com/bolt/core/blob/50e6f1baf283df112a820d97fbaea6d536079848/assets/js/app/editor/Components/Select.vue needs some additional attention, I leave that for a new issue/pull.

**Review by I-Valchev — APPROVED** [review]
Again, nice catch @Wieter .

Let's merge it in! Also merged into 4.1

**Pull request merged**
