### PR TITLE
dockefiles layer division

### PR DESCRIPTION
**Pull request by flug**
division of the dev layer from the potential production layer.
Changing the entrypoint for the dev part that installs the dependencies.
Change of the nginx part. Adding an argument to the build for
the different PDO drivers (mysql , postgresql etc... )

### CODE REVIEW

**Comment by bobdenotter** [comment]
Hi @flug, 

Let me know if this is GTG, and i'll merge it in! :-)

**Comment by bobdenotter** [comment]
Hi @flug, not to rush you, but please don't forget about this one. ;-)

**Comment by flug** [comment]
Yep, sorry about the time, I was a little rushed in my field, but I'll be able to handle the changes.

**Comment by bobdenotter** [comment]
Also closing this PR. See https://github.com/bolt/project/pull/15 for details.

**Pull request closed without merging**
