### PR TITLE
Use `setcontent` to filter with checkbox `true` or `false`

### PR DESCRIPTION
**Pull request by I-Valchev**

### CODE REVIEW

**Review by bobdenotter — APPROVED** [review]
Cool! 👍

**Comment by develth** [comment]
Thanks!
Any plans for a release? Or should i go for a cherry pick?

**Comment by bobdenotter** [comment]
This was merged into master, so it will be included in 4.2. If you need it now, you can indeed monkey-patch the fix in your project.

**Comment by develth** [comment]
Thanks @bobdenotter 
Is the master Branch usable for my e.g. testing stage, or is it more like a "development" branch?

**Comment by bobdenotter** [comment]
The latter. ;-)

**Pull request merged**
