### PR TITLE
 fix dockerfile argument flag and extra env $PATH

### PR DESCRIPTION
**Pull request by flug**

### CODE REVIEW

**Comment by bobdenotter** [comment]
@flug Cool, thanks! I assume we should make a similar change in the Project file, right? 

https://github.com/bolt/project/blob/master/docker/php/Dockerfile

**Comment by flug** [comment]
@bobdenotter Yes, I made a pr for that, too.

**Comment by bobdenotter** [comment]
@flug 🤦‍♂ Ok, i definetely need more coffee. Thanks!

**Comment by flug** [comment]
Me too 😂

**Pull request merged**
