### PR TITLE
$this->viewlessContentTypes should be a normal array. toArray() would…

### PR DESCRIPTION
**Pull request by simongroenewolt**
I think this fixes https://github.com/bolt/core/issues/1953

### CODE REVIEW

**Comment by LordSimal** [comment]
I can confirm, that this fixes the issue from #1953 
I tried it on my test instance.

Simon already explained the problem in the issue nicely.

**Review by bobdenotter — APPROVED** [review]
Thank you, @simongroenewolt! Great catch! 👍

**Comment by simongroenewolt** [comment]
FYI: A workaround for this issue is to change your configuration to not have any 'viewless' content types, so change every `viewless: true` to false in contenttypes.yaml. Disclaimer: I think this will only change them to be 'publicly visible' to people knowing the url, and linkable in twig by a developer, but it might have other side-effects I don't know of.

**Comment by sirTachyon** [comment]
Thanks for the bug fix! Much appreciated.

**Pull request merged**
