### PR TITLE
Make saving Ajaxy

### PR DESCRIPTION
**Pull request by Joossensei**
With this new feature the saving of a record will be done on the background using jQuery ajax.

Requires a lot of testing.

### CODE REVIEW

**Comment by Joossensei** [comment]
Gotta fix the Cypress tests first

**Comment by Joossensei** [comment]
The failing Cypress test seems to be failing only inside of Cypress not in a local checkout.

**Comment by Joossensei** [comment]
index

**Review by bobdenotter — APPROVED** [review]
Cool! 👍

**Pull request merged**
