### PR TITLE
Update config.yaml

### PR DESCRIPTION
**Pull request by eduardomart**
{contenttype}/{year}/{month}/ instead of year/month/contenttype

### CODE REVIEW

**Comment by I-Valchev** [comment]
hi @eduardomart , one thing I like about `year/month/contenttype` is that you can directly move folders between, say, multiple servers based on the date. 

With `contenttype/year/month`, of course, you can still do that but you'd have to replicate it for all CTs..

Is there a specific use case why `contenttype/year/moth` as the default will work better? 🙂

**Review by bobdenotter — APPROVED** [review]
@I-Valchev This is one of those things where I personally agree with you, but apparently the general consensus is otherwise. ;-)

Tests are failing, but that's because of #1851

**Comment by eduardomart** [comment]
@I-Valchev I am not sure I follow, if this is the default why do you have to replicate it?
While I prefer contenttype/year/month, I have no issue if the default is reverted to year/month/contenttype

**Comment by I-Valchev** [comment]
@eduardomart what I meant is that when people upload files by date, if you look at the file structure, you can copy files uploaded on certian days easier.

But, as @bobdenotter says, more people seem to prefer the contenttype/year/month default. Let's roll with it 🙂

**Pull request merged**
